name: lint, test and build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Starting node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: install node modules
        run: npm ci
      - name: lint typescript
        run: npm run lint:ts
      - name: lint scss
        run: npm run lint:scss
      - name: unit tests
        run: npm run test:unit
      - name: build storybook
        run: npm run build:storybook
      - name: build production project
        run: npm run build:prod
